server:
  port: 8002

spring:
  application:
    name: springboot-hungnt
  datasource:
    url: jdbc:mysql://192.168.1.101:3306/shopdev?serverTimezone=UTC  # Thêm `serverTimezone` để tránh lỗi múi giờ
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver  # Cập nhật driver mới

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  mail:
    port: 465
    host: xxxx
    password: aaaa
    username: aaaa
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true